### ISSUE TITLE
How do I determine the offset for a function that has already been decompiled?

### ISSUE THREAD

**Issue by dyc3** [pret/pokediamond#319]
I'm looking to use radare2 to help decompile this game. I want to be able to auto-name and type function signatures with stuff that has already been decompiled, but the C functions don't indicate what address the function originally came from.

**Comment by PikalaxALT** [comment]
The compilation process generates a file `arm9/build/diamond.us/arm9.elf.xMAP` which declares where all functions end up mapped in the compiled binary. You can also parse `arm9/build/diamond.us/arm9.elf` to get the same information in a more machine-friendly format.

**Comment by dyc3** [comment]
I don't see either of those files, but I do see a `pokediamond.us.nlf`

**Comment by LOuroboros** [comment]
> 
> 
> I don't see either of those files, but I do see a `pokediamond.us.nlf`

Both files show up normally on my end, for whatever that's worth.
I'm inclined to believe that a ROM wasn't built correctly on your end.

![Untitled3587](https://user-images.githubusercontent.com/4485172/109083703-29742d00-76e5-11eb-9a3d-5e63101d8562.png)
