### ISSUE TITLE
Decompile OS* functions

### ISSUE THREAD

**Issue by Demki** [pret/pokediamond#47]
A continuation of #7  

Create C definitions of all OS* functions. 
All methods defined in C will also have inline ASM copied from the dump, which will be applied if `MATCH_ASM` is defined.

List of OS* methods found:
- [x] OS_GetProcMode
- [x] OS_DisableInterrupts
- [x] OS_RestoreInterrupts
- [x] OS_AllocFromArenaLo
- [x] OS_AllocFromArenaHi
- [x] OS_SetArenaHi
- [x] OS_SetArenaLo
- [x] OS_GetArenaHi
- [x] OS_GetArenaLo
- [x] OS_AllocFromHeap
- [x] OS_CancelAlarm
- [x] OS_CreateAlarm
- [x] OS_CreateThread
- [x] OS_DestroyThread
- [x] OS_DisableInterrupts_IrqAndFiq
- [x] OS_DisableIrqMask
- [x] OS_DisableProtectionUnit
- [x] OS_DisableScheduler
- [x] OS_EnableInterrupts
- [x] OS_EnableIrqMask
- [x] OS_EnableProtectionUnit
- [x] OS_EnableScheduler
- [x] OS_ExitThread
- [x] OS_FreeToHeap
- [x] OS_GetConsoleType
- [x] OS_GetCpsrIrq
- [x] OS_GetDTCMAddress
- [x] OS_GetInitArenaHi
- [x] OS_GetInitArenaLo
- [x] OS_GetIrqFunction
- [x] OS_GetLockID
- [x] OS_GetLowEntropyData
- [x] OS_GetMacAddress
- [x] OS_GetOwnerInfo
- [x] OS_GetOwnerRtcOffset
- [x] OS_GetThreadPriority
- [x] OS_GetTick
- [x] OS_GetTickLo
- [x] OS_Halt
- [x] OS_Init
- [x] OS_InitAlarm
- [x] OS_InitArena
- [x] OS_InitArenaEx
- [x] OS_InitContext
- [x] OS_InitException
- [x] OS_InitIrqTable
- [x] OS_InitLock
- [x] OS_InitMessageQueue
- [x] OS_InitMutex
- [x] OS_InitReset
- [x] OS_InitThread
- [x] OS_InitTick
- [x] OS_InitVAlarm
- [x] OS_IrqDummy
- [x] OS_IrqHandler
- [x] OS_IrqHandler_ThreadSwitch
- [x] OS_IsAlarmAvailable
- [x] OS_IsRunOnEmulator
- [x] OS_IsThreadTerminated
- [x] OS_IsTickAvailable
- [x] OS_JamMessage
- [x] OS_JoinThread
- [x] OS_LoadContext
- [x] OS_LockCartridge
- [x] OS_LockMutex
- [x] OS_ReadMessage
- [x] OS_ReadOwnerOfLockWord
- [x] OS_ReceiveMessage
- [x] OS_ReleaseLockID
- [x] OS_RescheduleThread
- [x] OS_ResetRequestIrqMask
- [x] OS_ResetSystem
- [x] OS_RestoreInterrupts
- [x] OS_RestoreInterrupts_IrqAndFiq
- [x] OS_SaveContext
- [x] OS_SelectThread
- [x] OS_SendMessage
- [x] OS_SetAlarm
- [x] OS_SetDPermissionsForProtectionRegion
- [x] OS_SetIrqFunction
- [x] OS_SetIrqMask
- [x] OS_SetIrqStackChecker
- [x] OS_SetProtectionRegion1
- [x] OS_SetProtectionRegion2
- [x] OS_SetSwitchThreadCallback
- [x] OS_SetThreadDestructor
- [x] OS_SetThreadPriority
- [x] OS_Sleep
- [x] OS_SleepThread
- [x] OS_SNPrintf
- [x] OS_SpinWait
- [x] OS_SPrintf
- [x] OS_Terminate
- [x] OS_TryLockByWord
- [x] OS_TryLockCard
- [x] OS_TryLockCartridge
- [x] OS_TryLockMutex
- [x] OS_UnlockByWord
- [x] OS_UnlockCard
- [x] OS_UnlockCartridge
- [x] OS_UnlockCartridge
- [x] OS_UnlockMutex
- [x] OS_VSNPrintf
- [x] OS_VSPrintf
- [x] OS_WaitIrq
- [x] OS_WaitVBlankIntr
- [x] OS_WakeupThread
- [x] OS_WakeupThreadDirect
- [x] OS_YieldThread
- [x] OsCountZeroBits
- [x] OSi_AlarmHandler
- [x] OSi_AllocateCardBus
- [x] OSi_AllocateCartridgeBus
- [x] OSi_ArrangeTimer
- [x] OSi_CancelThreadAlarmForSleep
- [x] OSi_CommonCallback
- [x] OSi_CountUpTick
- [x] OSi_CpuClear32
- [x] OSi_DequeueItem
- [x] OSi_DisplayExContext
- [x] OSi_DoBoot
- [x] OSi_DoResetSystem
- [x] OSi_DoTryLockByWord
- [x] OSi_EnqueueTail
- [x] OSi_EnterDmaCallback
- [x] OSi_EnterTimerCallback
- [x] OSi_ExceptionHandler
- [x] OSi_ExitThread
- [x] OSi_ExitThread_ArgSpecified
- [x] OSi_ExitThread_Destroy
- [x] OSi_FreeCardBus
- [x] OSi_FreeCartridgeBus
- [x] OSi_GetAndDisplayContext
- [x] OSi_GetUnusedThreadId
- [x] OSi_IdleThreadProc
- [x] OSi_InitVramExclusive
- [x] OSi_InsertAlarm
- [x] OSi_InsertLinkToQueue
- [x] OSi_InsertThreadToList
- [x] OSi_IrqCallback
- [x] OSi_IrqDma0
- [x] OSi_IrqDma1
- [x] OSi_IrqDma2
- [x] OSi_IrqDma3
- [x] OSi_IrqTimer0
- [x] OSi_IrqTimer1
- [x] OSi_IrqTimer2
- [x] OSi_IrqTimer3
- [x] OSi_ReadCardRom32
- [x] OSi_ReloadRomData
- [x] OSi_RemoveLinkFromQueue
- [x] OSi_RemoveMutexLinkFromQueue
- [x] OSi_RemoveSpecifiedLinkFromQueue
- [x] OSi_RemoveThreadFromList
- [x] OSi_RescheduleThread
- [x] OSi_SendToPxi
- [x] OSi_SetExContext
- [x] OSi_SetTimer
- [x] OSi_SetTimerReserved
- [x] OSi_SleepAlarmCallback
- [x] OSi_TryLockVram
- [x] OSi_UnlockAllMutex
- [x] OSi_UnlockVram

**Comment by red031000** [comment]
done
